-- ============================================================================
-- MASTER SCHEMA DDL: CUSTOMER DATA PLATFORM (CDP) PRODUCTION MODEL
-- TARGET DATABASE: MySQL 8.x+
-- ============================================================================

CREATE DATABASE IF NOT EXISTS cdp_database;
USE cdp_database;

-- SET FOREIGN KEY CHECKS OFF TO ALLOW CLEAN DETERMINISTIC DROP LIFECYCLES
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS CDP_SEGMENT_MEMBERSHIP;
DROP TABLE IF EXISTS CDP_SEGMENT;
DROP TABLE IF EXISTS CDP_BEHAVIORAL_EVENT;
DROP TABLE IF EXISTS CDP_BEHAVIORAL_EVENT_TYPE;
DROP TABLE IF EXISTS CDP_PARTY_PREFERENCE;
DROP TABLE IF EXISTS CDP_PARTY_PREFERENCE_TYPE;
DROP TABLE IF EXISTS CDP_PARTY_CONTACT_MECH;
DROP TABLE IF EXISTS CDP_CONTACT_MECH_PURPOSE_TYPE;
DROP TABLE IF EXISTS CDP_POSTAL_ADDRESS;
DROP TABLE IF EXISTS CDP_ELECTRONIC_ADDRESS;
DROP TABLE IF EXISTS CDP_TELECOM_NUMBER;
DROP TABLE IF EXISTS CDP_EMAIL_ADDRESS;
DROP TABLE IF EXISTS CDP_CONTACT_MECHANISM;
DROP TABLE IF EXISTS CDP_CONTACT_MECH_TYPE;
DROP TABLE IF EXISTS CDP_PARTY_RELATIONSHIP;
DROP TABLE IF EXISTS CDP_PARTY_RELATIONSHIP_TYPE;
DROP TABLE IF EXISTS CDP_PARTY_ROLE;
DROP TABLE IF EXISTS CDP_ROLE_TYPE;
DROP TABLE IF EXISTS CDP_PARTY_ATTRIBUTE;
DROP TABLE IF EXISTS CDP_PARTY_MARKETING_METRIC;
DROP TABLE IF EXISTS CDP_PARTY_TAG;
DROP TABLE IF EXISTS CDP_PARTY_IDENTIFICATION;
DROP TABLE IF EXISTS CDP_PARTY_IDENTIFICATION_TYPE;
DROP TABLE IF EXISTS CDP_ORGANIZATION;
DROP TABLE IF EXISTS CDP_PERSON;
DROP TABLE IF EXISTS CDP_PARTY;
DROP TABLE IF EXISTS CDP_PARTY_TYPE;
SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================================
-- DOMAIN DOMAIN 1: CORE PROFILE & IDENTITY INHERITANCE LAYER
-- ============================================================================

CREATE TABLE CDP_PARTY_TYPE (
    PARTY_TYPE_ID VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (PARTY_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PARTY (
    PARTY_ID VARCHAR(40) NOT NULL,
    PARTY_TYPE_ID VARCHAR(40) NOT NULL,
    CREATED_STAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_STAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PARTY_ID),
    CONSTRAINT FK_PARTY_TYPE FOREIGN KEY (PARTY_TYPE_ID) REFERENCES CDP_PARTY_TYPE (PARTY_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PERSON (
    PARTY_ID VARCHAR(40) NOT NULL,
    FIRST_NAME VARCHAR(100) NULL,
    LAST_NAME VARCHAR(100) NULL,
    GENDER CHAR(1) NULL,
    BIRTH_DATE DATE NULL,
    PRIMARY KEY (PARTY_ID),
    CONSTRAINT FK_PERSON_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_ORGANIZATION (
    PARTY_ID VARCHAR(40) NOT NULL,
    ORGANIZATION_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (PARTY_ID),
    CONSTRAINT FK_ORG_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- DOMAIN DOMAIN 2: IDENTITY RESOLUTION & EXTENDED MUTABLE TRAITS
-- ============================================================================

CREATE TABLE CDP_PARTY_IDENTIFICATION_TYPE (
    PARTY_IDENT_TYPE_ID VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (PARTY_IDENT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PARTY_IDENTIFICATION (
    PARTY_ID VARCHAR(40) NOT NULL,
    PARTY_IDENT_TYPE_ID VARCHAR(40) NOT NULL,
    ID_VALUE VARCHAR(255) NOT NULL,
    PRIMARY KEY (PARTY_ID, PARTY_IDENT_TYPE_ID),
    INDEX IX_IDENT_VALUE (ID_VALUE),
    CONSTRAINT FK_PID_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PID_TYPE FOREIGN KEY (PARTY_IDENT_TYPE_ID) REFERENCES CDP_PARTY_IDENTIFICATION_TYPE (PARTY_IDENT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PARTY_TAG (
    PARTY_ID VARCHAR(40) NOT NULL,
    TAG_VALUE VARCHAR(100) NOT NULL,
    PRIMARY KEY (PARTY_ID, TAG_VALUE),
    CONSTRAINT FK_TAG_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PARTY_MARKETING_METRIC (
    PARTY_ID VARCHAR(40) NOT NULL,
    ORDERS_COUNT INT DEFAULT 0,
    TOTAL_SPENT DECIMAL(24,4) DEFAULT 0.0000,
    LAST_ORDER_ID VARCHAR(100) NULL,
    LAST_ORDER_NAME VARCHAR(100) NULL,
    LAST_CALCULATED_STAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PARTY_ID),
    CONSTRAINT FK_METRIC_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PARTY_ATTRIBUTE (
    PARTY_ID VARCHAR(40) NOT NULL,
    ATTR_NAME VARCHAR(100) NOT NULL,
    ATTR_VALUE TEXT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (PARTY_ID, ATTR_NAME),
    CONSTRAINT FK_ATTR_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- DOMAIN DOMAIN 3: COMPREHENSIVE ROLE-TO-ROLE RELATIONSHIP ENGINE
-- ============================================================================

CREATE TABLE CDP_ROLE_TYPE (
    ROLE_TYPE_ID VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (ROLE_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PARTY_ROLE (
    PARTY_ID VARCHAR(40) NOT NULL,
    ROLE_TYPE_ID VARCHAR(40) NOT NULL,
    FROM_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    THRU_DATE DATETIME NULL,
    PRIMARY KEY (PARTY_ID, ROLE_TYPE_ID, FROM_DATE),
    CONSTRAINT FK_PROLE_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PROLE_TYPE FOREIGN KEY (ROLE_TYPE_ID) REFERENCES CDP_ROLE_TYPE (ROLE_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PARTY_RELATIONSHIP_TYPE (
    PARTY_RELATIONSHIP_TYPE_ID VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (PARTY_RELATIONSHIP_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PARTY_RELATIONSHIP (
    PARTY_ID_FROM VARCHAR(40) NOT NULL,
    ROLE_TYPE_ID_FROM VARCHAR(40) NOT NULL,
    FROM_DATE_FROM DATETIME NOT NULL,
    PARTY_ID_TO VARCHAR(40) NOT NULL,
    ROLE_TYPE_ID_TO VARCHAR(40) NOT NULL,
    FROM_DATE_TO DATETIME NOT NULL,
    PARTY_RELATIONSHIP_TYPE_ID VARCHAR(40) NOT NULL,
    FROM_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    THRU_DATE DATETIME NULL,
    PRIMARY KEY (PARTY_ID_FROM, ROLE_TYPE_ID_FROM, FROM_DATE_FROM, 
                 PARTY_ID_TO, ROLE_TYPE_ID_TO, FROM_DATE_TO, 
                 PARTY_RELATIONSHIP_TYPE_ID, FROM_DATE),
    CONSTRAINT FK_PREL_ROLE_FROM FOREIGN KEY (PARTY_ID_FROM, ROLE_TYPE_ID_FROM, FROM_DATE_FROM) 
        REFERENCES CDP_PARTY_ROLE (PARTY_ID, ROLE_TYPE_ID, FROM_DATE),
    CONSTRAINT FK_PREL_ROLE_TO FOREIGN KEY (PARTY_ID_TO, ROLE_TYPE_ID_TO, FROM_DATE_TO) 
        REFERENCES CDP_PARTY_ROLE (PARTY_ID, ROLE_TYPE_ID, FROM_DATE),
    CONSTRAINT FK_PREL_TYPE FOREIGN KEY (PARTY_RELATIONSHIP_TYPE_ID) 
        REFERENCES CDP_PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- DOMAIN DOMAIN 4: UNIFIED OMNI-CHANNEL ENGAGEMENT VECTORS
-- ============================================================================

CREATE TABLE CDP_CONTACT_MECH_TYPE (
    CONTACT_MECH_TYPE_ID VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (CONTACT_MECH_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_CONTACT_MECHANISM (
    CONTACT_MECH_ID VARCHAR(40) NOT NULL,
    CONTACT_MECH_TYPE_ID VARCHAR(40) NOT NULL,
    PRIMARY KEY (CONTACT_MECH_ID),
    CONSTRAINT FK_CMECH_TYPE FOREIGN KEY (CONTACT_MECH_TYPE_ID) REFERENCES CDP_CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_EMAIL_ADDRESS (
    CONTACT_MECH_ID VARCHAR(40) NOT NULL,
    EMAIL_ADDRESS VARCHAR(255) NOT NULL,
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (CONTACT_MECH_ID),
    UNIQUE INDEX UQ_EMAIL_STR (EMAIL_ADDRESS),
    CONSTRAINT FK_EMAIL_CMECH FOREIGN KEY (CONTACT_MECH_ID) REFERENCES CDP_CONTACT_MECHANISM (CONTACT_MECH_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_TELECOM_NUMBER (
    CONTACT_MECH_ID VARCHAR(40) NOT NULL,
    COUNTRY_CODE VARCHAR(10) NULL,
    AREA_CODE VARCHAR(10) NULL,
    CONTACT_NUMBER VARCHAR(40) NOT NULL,
    PRIMARY KEY (CONTACT_MECH_ID),
    CONSTRAINT FK_PHONE_CMECH FOREIGN KEY (CONTACT_MECH_ID) REFERENCES CDP_CONTACT_MECHANISM (CONTACT_MECH_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_ELECTRONIC_ADDRESS (
    CONTACT_MECH_ID VARCHAR(40) NOT NULL,
    SOCIAL_HANDLE VARCHAR(100) NOT NULL,
    PLATFORM_NAME VARCHAR(50) NOT NULL, -- 'INSTAGRAM', 'TIKTOK', etc.
    PRIMARY KEY (CONTACT_MECH_ID),
    CONSTRAINT FK_EADDR_CMECH FOREIGN KEY (CONTACT_MECH_ID) REFERENCES CDP_CONTACT_MECHANISM (CONTACT_MECH_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_POSTAL_ADDRESS (
    CONTACT_MECH_ID VARCHAR(40) NOT NULL,
    TO_NAME VARCHAR(255) NULL,        -- Captures the attention line or company name context easily
    ADDRESS1 TEXT NOT NULL,
    ADDRESS2 TEXT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE_PROVINCE_GEO_ID VARCHAR(40) NULL,
    COUNTRY_GEO_ID VARCHAR(40) NOT NULL,
    POSTAL_CODE VARCHAR(20) NOT NULL,
    PRIMARY KEY (CONTACT_MECH_ID),
    CONSTRAINT FK_POSTAL_CMECH FOREIGN KEY (CONTACT_MECH_ID) REFERENCES CDP_CONTACT_MECHANISM (CONTACT_MECH_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_CONTACT_MECH_PURPOSE_TYPE (
    CONTACT_MECH_PURPOSE_TYPE_ID VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (CONTACT_MECH_PURPOSE_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PARTY_CONTACT_MECH (
    PARTY_ID VARCHAR(40) NOT NULL,
    CONTACT_MECH_ID VARCHAR(40) NOT NULL,
    CONTACT_MECH_PURPOSE_TYPE_ID VARCHAR(40) NOT NULL,
    FROM_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    THRU_DATE DATETIME NULL,
    PRIMARY KEY (PARTY_ID, CONTACT_MECH_ID, CONTACT_MECH_PURPOSE_TYPE_ID, FROM_DATE),
    CONSTRAINT FK_PCM_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PCM_CMECH FOREIGN KEY (CONTACT_MECH_ID) REFERENCES CDP_CONTACT_MECHANISM (CONTACT_MECH_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PCM_PURPOSE FOREIGN KEY (CONTACT_MECH_PURPOSE_TYPE_ID) REFERENCES CDP_CONTACT_MECH_PURPOSE_TYPE (CONTACT_MECH_PURPOSE_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- DOMAIN DOMAIN 5: MARKETING CONSENT & BEHAVIORAL AUDIT LAYERS
-- ============================================================================

CREATE TABLE CDP_PARTY_PREFERENCE_TYPE (
    PARTY_PREF_TYPE_ID VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (PARTY_PREF_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_PARTY_PREFERENCE (
    PARTY_ID VARCHAR(40) NOT NULL,
    PARTY_PREF_TYPE_ID VARCHAR(40) NOT NULL,
    PREFERENCE_VALUE VARCHAR(100) NOT NULL, -- 'subscribed', 'unsubscribed', etc.
    FROM_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    THRU_DATE DATETIME NULL,
    PRIMARY KEY (PARTY_ID, PARTY_PREF_TYPE_ID, FROM_DATE),
    CONSTRAINT FK_PREF_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PREF_TYPE FOREIGN KEY (PARTY_PREF_TYPE_ID) REFERENCES CDP_PARTY_PREFERENCE_TYPE (PARTY_PREF_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_BEHAVIORAL_EVENT_TYPE (
    EVENT_TYPE_ID VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    PRIMARY KEY (EVENT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_BEHAVIORAL_EVENT (
    EVENT_ID VARCHAR(40) NOT NULL,
    PARTY_ID VARCHAR(40) NOT NULL,
    EVENT_TYPE_ID VARCHAR(40) NOT NULL,
    EVENT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    METRIC_VALUE DECIMAL(24,4) NULL,
    PAYLOAD_JSON JSON NULL,               -- Handles full schema unstructured tracking details gracefully
    PRIMARY KEY (EVENT_ID),
    INDEX IX_BEH_PARTY_DATE (PARTY_ID, EVENT_DATE),
    CONSTRAINT FK_BEH_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BEH_TYPE FOREIGN KEY (EVENT_TYPE_ID) REFERENCES CDP_BEHAVIORAL_EVENT_TYPE (EVENT_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_SEGMENT (
    SEGMENT_ID VARCHAR(40) NOT NULL,
    SEGMENT_NAME VARCHAR(100) NOT NULL,
    RULE_LOGIC_EXPRESSION TEXT NOT NULL,  -- Keeps dynamic condition parameters structured for evaluators
    PRIMARY KEY (SEGMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CDP_SEGMENT_MEMBERSHIP (
    SEGMENT_ID VARCHAR(40) NOT NULL,
    PARTY_ID VARCHAR(40) NOT NULL,
    EVALUATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (SEGMENT_ID, PARTY_ID, EVALUATED_DATE),
    CONSTRAINT FK_SMEM_SEG FOREIGN KEY (SEGMENT_ID) REFERENCES CDP_SEGMENT (SEGMENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SMEM_PARTY FOREIGN KEY (PARTY_ID) REFERENCES CDP_PARTY (PARTY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- SEED DATA PRE-POPULATION LOOKUPS
-- ============================================================================

INSERT INTO CDP_PARTY_TYPE (PARTY_TYPE_ID, DESCRIPTION) VALUES 
('PERSON', 'Individual Consumer Human Identity Profile'),
('ORGANIZATION', 'Corporate Enterprise Merchant Account Client');

INSERT INTO CDP_ROLE_TYPE (ROLE_TYPE_ID, DESCRIPTION) VALUES 
('CUSTOMER', 'Retail Client Consumer Entity Account'),
('EMPLOYER', 'Corporate B2B Host Workspace Firm'),
('EMPLOYEE', 'Affiliated Workforce Operative Personnel');

INSERT INTO CDP_PARTY_IDENTIFICATION_TYPE (PARTY_IDENT_TYPE_ID, DESCRIPTION) VALUES 
('SHOPIFY_CUST_ID', 'Shopify Base Numeric Natural Customer ID Reference Key'),
('SHOPIFY_MULTIPASS_ID', 'Shopify SSO Multipass Gateway Auth String Anchor'),
('SHOPIFY_GRAPHQL_GID', 'Shopify Native Global Admin API Object Tracking Code');

INSERT INTO CDP_CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, DESCRIPTION) VALUES 
('POSTAL_ADDRESS', 'Physical Street Routing Delivery Location Attributes'),
('EMAIL_ADDRESS', 'Electronic SMTP Mail Gateway Communication Paths'),
('TELECOM_NUMBER', 'International Telephone Dialing Communication Vectors'),
('ELECTRONIC_ADDRESS', 'Social Network Channel Communication Paths');

INSERT INTO CDP_CONTACT_MECH_PURPOSE_TYPE (CONTACT_MECH_PURPOSE_TYPE_ID, DESCRIPTION) VALUES 
('DEFAULT_LOCATION', 'Master Core Communication Target Selection Flag'),
('SHIPPING_LOCATION', 'Default Logistics Parcel Delivery Transit Routing Destination'),
('BILLING_LOCATION', 'Financial Transaction Ledger Statement Invoicing Hub');

INSERT INTO CDP_PARTY_PREFERENCE_TYPE (PARTY_PREF_TYPE_ID, DESCRIPTION) VALUES 
('EMAIL_MARKETING', 'Electronic Direct Newsletters Marketing Broadcast Consent Bounds'),
('SMS_MARKETING', 'Mobile Cellular Short-Messaging Marketing Telephony Broadcast Consent');

INSERT INTO CDP_PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, DESCRIPTION) VALUES 
('EMPLOYMENT', 'B2B Enterprise Staff Hierarchy Human Association Grid'),
('PROFILE_MERGE', 'Identity Resolution Audit Consolidated Duplicate Subordination Record');

INSERT INTO CDP_BEHAVIORAL_EVENT_TYPE (EVENT_TYPE_ID, DESCRIPTION) VALUES 
('page_viewed', 'Online Storefront Interaction Point Trigger Event Trace'),
('product_purchased', 'Commerce Lifecycle Check-out Order Complete Capture Transaction');